---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: goof
  name: goof
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goof
  template:
    metadata:
      labels:
        app: goof
    spec:
      containers:
      - image: ${DOCKER_ACCOUNT}/java-goof:latest
        imagePullPolicy: Always
        name: java-goof
        livenessProbe:
          exec:
            command:
              - /usr/bin/check-status
              - -l
        resources:
          limits:
            memory: 2Gb
            cpu: 2
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          runAsUser: 65534 #nobody
          runAsGroup: 65534 #nobody
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: goof
  name: goof
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 0.0.0.0/0
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: goof
